START TRANSACTION;

CREATE TABLE contact
(
    contactId int GENERATED BY DEFAULT AS IDENTITY,
    firstName varchar(64) NOT NULL,
    lastName varchar(64) NOT NULL,
    dateAdded timestamp NOT NULL,
    dateUpdated timestamp,

    CONSTRAINT pk_contact PRIMARY KEY (contactId)
);


CREATE TABLE address
(
    addressId int GENERATED BY DEFAULT AS IDENTITY,
    contactId int NOT NULL,
    addressType varchar(10) NOT NULL,
    addressOtherDescription varchar(100), 
    addressLine1 varchar(100) NOT NULL,
    addressLine2 varchar(100),
    city varchar(64) NOT NULL,
    state varchar(24) NOT NULL,
    zipCode varchar(10) NOT NULL,

    CONSTRAINT pk_address PRIMARY KEY (addressId),
    CONSTRAINT fk_address_contact FOREIGN KEY (contactId) REFERENCES contact (contactId),
    CONSTRAINT chk_addressType CHECK (addressType IN ('Home', 'Work', 'Shipping', 'Billing', 'Other')),
    CONSTRAINT chk_addressOtherDescription CHECK (
        (addressType = 'Other' AND addressOtherDescription IS NOT NULL)
        OR (addressType <> 'Other' AND addressOtherDescription IS NULL)
    )

);


CREATE TABLE phone
(
    phoneId int GENERATED BY DEFAULT AS IDENTITY,
    contactId int NOT NULL,
    phoneType varchar(10) NOT NULL,
    phoneOtherDescription varchar(100),
    phoneNumber varchar(10) NOT NULL,

    CONSTRAINT pk_phone PRIMARY KEY (phoneId),
    CONSTRAINT fk_phone_contact FOREIGN KEY (contactId) REFERENCES contact (contactId),
    CONSTRAINT chk_phoneType CHECK (phoneType IN ('Home', 'Work', 'Mobile', 'Other')),
    CONSTRAINT chk_phoneOtherDescription CHECK (
        (phoneType = 'Other' AND phoneOtherDescription IS NOT NULL)
        OR (phoneType <> 'Other' AND phoneOtherDescription IS NULL)
    )

);

CREATE TABLE email
(
    emailId int GENERATED BY DEFAULT AS IDENTITY,
    contactId int NOT NULL,
    emailType varchar(10) NOT NULL,
    emailOtherDescription varchar(100),
    emailAddress varchar(100) NOT NULL,

    CONSTRAINT pk_email PRIMARY KEY (emailId),
    CONSTRAINT fk_email_contact FOREIGN KEY (contactId) REFERENCES contact (contactId),
    CONSTRAINT chk_emailType CHECK (emailType IN ('Home', 'Work', 'Other')),
    CONSTRAINT chk_emailOtherDescription CHECK (
        (emailType = 'Other' AND emailOtherDescription IS NOT NULL)
        OR (emailType <> 'Other' AND emailOtherDescription IS NULL)
    )

);


INSERT INTO contact (firstName, lastName, dateAdded)
VALUES ('David', 'Pfaltzgraff-Carlson', current_date);

INSERT INTO address (contactId, addressType, addressLine1, city, state, zipCode)
VALUES ((SELECT contactId FROM contact WHERE firstName = 'David' AND lastName = 'Pfaltzgraff-Carlson'),
         'Home', '100 Busy Street', 'Cincinnati', 'Ohio', '45241');

INSERT INTO phone (contactId, phoneType, phoneNumber)
VALUES ((SELECT contactId FROM contact WHERE firstName = 'David' AND lastName = 'Pfaltzgraff-Carlson'),
         'Mobile', '5135551212');

INSERT INTO email (contactId, emailType, emailOtherDescription, emailAddress)
VALUES ((SELECT contactId FROM contact WHERE firstName = 'David' AND lastName = 'Pfaltzgraff-Carlson'),
         'Other', 'School', 'david.pc@techelevator.com');



COMMIT TRANSACTION;